# chapter 12

apiVersion: batch/v1
kind: CronJob
metadata:
  name: example-cron

spec:
  schedule: "0 */5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: batch-job
              image: gcr.io/kuar-demo/kuard-amd64:blue
              command:
                - "/kuard"
              args:
                - "--keygen-enable"
                - "--keygen-exit-on-complete"
                - "--keygen-num-to-gen=10"
          restartPolicy: OnFailure
