# Chapter 12

apiVersion: batch/v1
kind: Job
metadata:
  name: oneshot

spec:
  template:
    spec:
      containers:
        - name: kuard
          image: gcr.io/kuar-demo/kuard-amd64:blue
          imagePullPolicy: Always
          command:
            - "/kuard" # il faut absolument le - à la con car command est un tableau
          args:
            - "--keygen-enable"
            - "--keygen-exit-on-complete"
            - "--keygen-exit-code=1"
            - "--keygen-num-to-gen=2"
      restartPolicy: Never
