# chapter 7
# https://kind.sigs.k8s.io/docs/user/configuration/#extra-port-mappings
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: issou

nodes:
- role: control-plane
  image: kindest/node:v1.27.1
  extraPortMappings:
  - containerPort: 30950 # port sur mon conteneur
    hostPort: 80 #port sur mon pc
