apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"6"},"creationTimestamp":"2023-06-26T09:41:35Z","generation":9,"labels":{"run":"kuard"},"name":"kuard","namespace":"default","resourceVersion":"34494","uid":"0a32ab7e-a120-40a3-a36a-247e3c5e73c1"},"spec":{"progressDeadlineSeconds":600,"replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"run":"kuard"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2023-06-26T12:44:53+02:00","kubernetes.io/change-cause":"update to kuard green!"},"creationTimestamp":null,"labels":{"run":"kuard"}},"spec":{"containers":[{"image":"gcr.io/kuar-demo/kuard-arm64:green","imagePullPolicy":"IfNotPresent","name":"kuard","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":3,"conditions":[{"lastTransitionTime":"2023-06-26T10:07:11Z","lastUpdateTime":"2023-06-26T10:07:11Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2023-06-26T09:41:35Z","lastUpdateTime":"2023-06-26T10:44:56Z","message":"ReplicaSet \"kuard-55577fcb9d\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":9,"readyReplicas":3,"replicas":3,"updatedReplicas":3}}
  creationTimestamp: "2023-06-26T09:41:35Z"
  generation: 10
  labels:
    run: kuard
  name: kuard
  namespace: default
  resourceVersion: "35030"
  uid: 0a32ab7e-a120-40a3-a36a-247e3c5e73c1
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 42 #issou
  selector:
    matchLabels:
      run: kuard
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-06-26T12:44:53+02:00"
        kubernetes.io/change-cause: update to kuard blue!
      creationTimestamp: null
      labels:
        run: kuard
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-arm64:blue
        imagePullPolicy: IfNotPresent
        name: kuard
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2023-06-26T10:07:11Z"
    lastUpdateTime: "2023-06-26T10:07:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-06-26T09:41:35Z"
    lastUpdateTime: "2023-06-26T10:49:06Z"
    message: ReplicaSet "kuard-666b69c579" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 10
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
