# chapitre 13 p 151
apiVersion: v1
kind: Pod
metadata:
  name: kuard-config
spec:
  containers:
    - name: test-container
      image: gcr.io/kuar-demo/kuard-arm64:blue
      imagePullPolicy: IfNotPresent
      command:
        - "/kuard"
        - "${EXTRA_PARAM}"
      env:
        - name: ANOTHER_PARAM # env var inside the container
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: another-param

        - name: EXTRA_PARAM # env var passed to the command when starting the container
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: extra-param

      volumeMounts:
        # mounting CM as a set of files
        - name: config-volume
          mountPath: /config

  volumes:
    - name: config-volume
      configMap:
        name: my-config

  restartPolicy: Never
